// build.mjs — turns the .jsx sources into plain JS so the browser doesn't have
// to carry Babel.
//
// These files are classic scripts sharing one global scope: no imports, no
// exports, and they reach for each other's top-level names directly. So this
// concatenates them in load order and *transforms* rather than bundles —
// esbuild's --bundle would give each file its own module scope and every
// cross-file reference would come back undefined.

import { transform } from "esbuild";
import { readFile, writeFile, mkdir, copyFile, readdir } from "node:fs/promises";
import { dirname } from "node:path";

const VERSION = JSON.parse(await readFile("package.json", "utf8")).version;

// The WASM codecs are vendored rather than pulled from a CDN, because the app
// claims to work offline and a CDN would make that false again for anyone who
// turned the option on. Copied verbatim: every file below resolves its
// imports and its .wasm relative to itself, so nothing needs rewriting.
// @jsquash/oxipng's own optimise.js is skipped — it imports a bare specifier
// for a multi-threaded path that needs COOP/COEP headers GitHub Pages does not
// send, so oxipng.js here wraps the single-threaded codec directly.
const VENDOR = [
  ["@jsquash/jpeg/encode.js",                     "vendor/jpeg/encode.js"],
  ["@jsquash/jpeg/meta.js",                       "vendor/jpeg/meta.js"],
  ["@jsquash/jpeg/utils.js",                      "vendor/jpeg/utils.js"],
  ["@jsquash/jpeg/codec/pre.js",                  "vendor/jpeg/codec/pre.js"],
  ["@jsquash/jpeg/codec/enc/mozjpeg_enc.js",      "vendor/jpeg/codec/enc/mozjpeg_enc.js"],
  ["@jsquash/jpeg/codec/enc/mozjpeg_enc.wasm",    "vendor/jpeg/codec/enc/mozjpeg_enc.wasm"],
  ["@jsquash/oxipng/codec/pkg/squoosh_oxipng.js",     "vendor/oxipng/squoosh_oxipng.js"],
  ["@jsquash/oxipng/codec/pkg/squoosh_oxipng_bg.wasm", "vendor/oxipng/squoosh_oxipng_bg.wasm"],
];

let vendored = 0;
for (const [from, to] of VENDOR) {
  await mkdir(dirname(to), { recursive: true });
  await copyFile("node_modules/" + from, to);
  vendored++;
}
// The service worker has to precache these by hand, and that list silently
// fell behind once already — the codecs shipped, but offline only worked if
// you had used max compression while online first.
// Walks the directory rather than VENDOR, so the hand-written oxipng.js
// wrapper is covered too — it is not copied by the loop above but the app
// cannot compress a PNG without it.
const sw = await readFile("sw.js", "utf8");
const walk = async dir => (await Promise.all(
  (await readdir(dir, { withFileTypes: true })).map(e =>
    e.isDirectory() ? walk(`${dir}/${e.name}`) : [`${dir}/${e.name}`]))).flat();
const missing = (await walk("vendor")).filter(f => !sw.includes(`"./${f}"`));
if (missing.length) {
  console.error(`sw.js SHELL is missing:\n  ${missing.join("\n  ")}`);
  process.exit(1);
}
console.log(`vendor/              ${vendored} codec files copied, all in sw.js SHELL`);

const BUNDLES = [
  { out: "bundle.js", minify: true,
    src: ["processor.jsx", "copy.jsx", "icons.jsx", "convert.jsx", "other-tools.jsx", "app.jsx"] },
  // The test page needs the engine and the convert module, plus the cases
  // themselves in the same scope so they can read ICO_SIZES and friends.
  { out: "selftest.bundle.js", minify: false,
    src: ["processor.jsx", "convert.jsx", "other-tools.jsx", "selftest-cases.js"] },
];

for (const { out, src, minify } of BUNDLES) {
  const parts = await Promise.all(src.map(f => readFile(f, "utf8")));
  let joined = src.map((f, i) => `// ── ${f} ${"─".repeat(Math.max(0, 60 - f.length))}\n${parts[i]}`).join("\n");
  // The footer used to carry its own copy of the version, so bumping
  // package.json quietly left the app claiming the old one.
  joined = joined.replaceAll("__PIXL_VERSION__", VERSION);
  const result = await transform(joined, {
    loader: "jsx",
    // Not "module": these run as classic scripts and must keep sloppy-mode
    // global scope, which is how the files see each other.
    format: undefined,
    minify,
    target: "es2020",
    legalComments: "none",
  });
  if (result.warnings.length) {
    for (const w of result.warnings) console.warn(`  warn ${w.text}`);
  }
  await writeFile(out, `// Generated by build.mjs — edit the .jsx sources, not this file.\n${result.code}`);
  const kb = n => (n / 1024).toFixed(1) + " KB";
  console.log(`${out.padEnd(20)} ${src.length} files → ${kb(result.code.length)}`);
}
