// build.mjs — turns the .jsx sources into plain JS so the browser doesn't have
// to carry Babel.
//
// These files are classic scripts sharing one global scope: no imports, no
// exports, and they reach for each other's top-level names directly. So this
// concatenates them in load order and *transforms* rather than bundles —
// esbuild's --bundle would give each file its own module scope and every
// cross-file reference would come back undefined.

import { transform } from "esbuild";
import { readFile, writeFile } from "node:fs/promises";

const BUNDLES = [
  { out: "bundle.js", minify: true,
    src: ["processor.jsx", "copy.jsx", "icons.jsx", "convert.jsx", "other-tools.jsx", "app.jsx"] },
  // The test page needs the engine and the convert module, plus the cases
  // themselves in the same scope so they can read ICO_SIZES and friends.
  { out: "selftest.bundle.js", minify: false,
    src: ["processor.jsx", "convert.jsx", "selftest-cases.js"] },
];

for (const { out, src, minify } of BUNDLES) {
  const parts = await Promise.all(src.map(f => readFile(f, "utf8")));
  const joined = src.map((f, i) => `// ── ${f} ${"─".repeat(Math.max(0, 60 - f.length))}\n${parts[i]}`).join("\n");
  const result = await transform(joined, {
    loader: "jsx",
    // Not "module": these run as classic scripts and must keep sloppy-mode
    // global scope, which is how the files see each other.
    format: undefined,
    minify,
    target: "es2020",
    legalComments: "none",
  });
  if (result.warnings.length) {
    for (const w of result.warnings) console.warn(`  warn ${w.text}`);
  }
  await writeFile(out, `// Generated by build.mjs — edit the .jsx sources, not this file.\n${result.code}`);
  const kb = n => (n / 1024).toFixed(1) + " KB";
  console.log(`${out.padEnd(20)} ${src.length} files → ${kb(result.code.length)}`);
}
