// copy.jsx — i18n strings

const COPY = {
  en: {
    appTitle1: "Pixl",
    appTitle2: "Tweak",
    appSub: "Convert, resize, compress and crop your images — ",

    tabs: {
      convert: "Convert",
      resize: "Resize",
      compress: "Compress",
      crop: "Crop & Rotate",
    },

    drop: {
      title: "Drop your images here",
      hint: "Drag images or folders, or click to browse — we'll take care of the rest.",
      browse: "Browse files",
      folder: "Choose folder",
      sample: "Try with samples",
      supported: "Supported formats",
    },

    convert: {
      heading: "Convert format",
      format: "Target format",
      quality: "Quality",
      qualityHint: "Lower = smaller file, higher = sharper",
      preserve: "Keep metadata (EXIF)",
      colorProfile: "Embed sRGB profile",
      transparent: "Preserve transparency",
      output: "Output folder",
      outputPath: "~/Pictures/Pixl Tweak",
      change: "Change",
      total: "Total saved",
      go: "Convert",
      moreFiles: "Add more",
      converting: "Converting…",
      elapsed: "elapsed",
      convertingSub: "Working through your queue, hang tight.",
      doneTitle: "All done!",
      doneSub: "Converted {n} images, saved {saved}.",
      openFolder: "Open folder",
      again: "Convert more",
      filesIn: "files in queue",
      icoKeepOriginal: "Keep Original Resolution",
      icoIncludeSource: "Include source size in output",
      icoSizes: "ICO sizes to export",
      icoSizesHint: "Each size exports to its own folder",
      mergePDF: "Merge into one PDF file",
      clearAll: "Remove all files",
    },

    resize: {
      heading: "Resize dimensions",
      preset: "Preset",
      presets: [
        ["Original", "—"],
        ["HD", "1920×1080"],
        ["Web", "1280×720"],
        ["Square", "1080×1080"],
        ["Story", "1080×1920"],
        ["Custom", "any"],
      ],
      width: "Width",
      height: "Height",
      lock: "Lock aspect ratio",
      fit: "Fit mode",
      fits: ["Contain", "Cover", "Stretch"],
      fitTooltips: [
        "Fits inside, no crop",
        "Fills area, crops edges",
        "Exact size, may distort",
      ],
      upscale: "Allow upscaling",
      outputFormat: "Output format",
      transparent: "Preserve transparency",
      apply: "Apply",
    },

    compress: {
      heading: "Compress file size",
      target: "Target",
      targets: ["Web", "Email", "Print", "Custom"],
      quality: "Quality",
      before: "Before",
      after: "After",
      savings: "Estimated savings",
      originalQuality: "original quality",
      filesSingular: "file",
      filesPlural: "files",
      outputFormat: "Output format",
      reduceColors: "Reduce max colors (PNG)",
      reduceColorsHint: "Quantizes the palette — ideal for logos and icons",
      maxColors: "Max colors",
      start: "Start",
    },

    crop: {
      heading: "Crop & rotate",
      ratio: "Aspect ratio",
      ratios: ["Free", "1:1", "4:3", "16:9", "3:4", "9:16"],
      rotate: "Rotate",
      flipH: "Flip horizontal",
      flipV: "Flip vertical",
      reset: "Reset",
      apply: "Apply",
    },

    common: {
      cancel: "Cancel",
      go: "Start",
      addMore: "Add files",
      remove: "Remove",
      processing: "Processing",
      ready: "Ready",
      saved: "saved",
    },

    footer: {
      ready: "Ready",
      offline: "Works offline",
      version: "v2.4.1",
    },
  },

  es: {
    appTitle1: "Pixl",
    appTitle2: "Tweak",
    appSub: "Convierte, redimensiona, comprime y recorta tus imágenes — ",

    tabs: {
      convert: "Convertir",
      resize: "Redimensionar",
      compress: "Comprimir",
      crop: "Recortar",
    },

    drop: {
      title: "Suelta tus imágenes aquí",
      hint: "Arrastra imágenes o carpetas, o haz clic para explorar — del resto nos encargamos nosotros.",
      browse: "Buscar archivos",
      folder: "Elegir carpeta",
      sample: "Probar con ejemplos",
      supported: "Formatos compatibles",
    },

    convert: {
      heading: "Convertir formato",
      format: "Formato de salida",
      quality: "Calidad",
      qualityHint: "Menor = archivo más ligero, mayor = más nítido",
      preserve: "Conservar metadatos (EXIF)",
      colorProfile: "Incrustar perfil sRGB",
      transparent: "Conservar transparencia",
      output: "Carpeta de salida",
      outputPath: "~/Imágenes/Pixl Tweak",
      change: "Cambiar",
      total: "Total ahorrado",
      go: "Convertir",
      moreFiles: "Agregar más",
      converting: "Convirtiendo…",
      elapsed: "transcurrido",
      convertingSub: "Procesando tu cola, un momento.",
      doneTitle: "¡Listo!",
      doneSub: "Se convirtieron {n} imágenes, ahorraste {saved}.",
      openFolder: "Abrir carpeta",
      again: "Convertir más",
      filesIn: "archivos en la cola",
      icoKeepOriginal: "Mantener resolución original",
      icoIncludeSource: "Incluir tamaño original en output",
      icoSizes: "Tamaños ICO a exportar",
      icoSizesHint: "Cada tamaño se exportará en su propia carpeta",
      mergePDF: "Unir en un solo PDF",
      clearAll: "Quitar todo",
    },

    resize: {
      heading: "Cambiar dimensiones",
      preset: "Predefinido",
      presets: [
        ["Original", "—"],
        ["HD", "1920×1080"],
        ["Web", "1280×720"],
        ["Cuadrado", "1080×1080"],
        ["Historia", "1080×1920"],
        ["Personalizado", "cualquiera"],
      ],
      width: "Ancho",
      height: "Alto",
      lock: "Bloquear proporción",
      fit: "Modo de ajuste",
      fits: ["Contener", "Cubrir", "Estirar"],
      fitTooltips: [
        "Ajusta sin recortar",
        "Rellena, puede recortar",
        "Exacto, puede distorsionar",
      ],
      upscale: "Permitir ampliación",
      outputFormat: "Formato de salida",
      transparent: "Conservar transparencia",
      apply: "Aplicar",
    },

    compress: {
      heading: "Comprimir tamaño",
      target: "Destino",
      targets: ["Web", "Correo", "Impresión", "Personalizado"],
      quality: "Calidad",
      before: "Antes",
      after: "Después",
      savings: "Ahorro estimado",
      originalQuality: "calidad original",
      filesSingular: "archivo",
      filesPlural: "archivos",
      outputFormat: "Formato de salida",
      reduceColors: "Reducir colores máximos (PNG)",
      reduceColorsHint: "Cuantiza la paleta — ideal para logos e iconos",
      maxColors: "Máximo de colores",
      start: "Comprimir",
    },

    crop: {
      heading: "Recortar y rotar",
      ratio: "Proporción",
      ratios: ["Libre", "1:1", "4:3", "16:9", "3:4", "9:16"],
      rotate: "Rotar",
      flipH: "Voltear horizontal",
      flipV: "Voltear vertical",
      reset: "Restablecer",
      apply: "Aplicar",
    },

    common: {
      cancel: "Cancelar",
      go: "Iniciar",
      addMore: "Añadir archivos",
      remove: "Quitar",
      processing: "Procesando",
      ready: "Listo",
      saved: "ahorrados",
    },

    footer: {
      ready: "Listo",
      offline: "Funciona sin conexión",
      version: "v2.4.1",
    },
  },
};

window.COPY = COPY;
