// copy.jsx — i18n strings

const COPY = {
  en: {
    appTitle1: "Pixl",
    appTitle2: "Tweak",
    appSub: "Convert, resize, compress and crop your images — ",

    tabs: {
      convert: "Convert",
      resize: "Resize",
      compress: "Compress",
      crop: "Crop & Rotate",
    },

    drop: {
      title: "Drop your images here",
      hint: "Drag images or folders, or click to browse — we'll take care of the rest.",
      browse: "Browse files",
      folder: "Choose folder",
      sample: "Try with samples",
      supported: "Supported formats",
    },

    convert: {
      heading: "Convert format",
      format: "Target format",
      quality: "Quality",
      qualityHint: "Lower = smaller file, higher = sharper",
      transparent: "Preserve transparency",
      maxCompress: "Maximum compression",
      maxCompressHint: "MozJPEG and OxiPNG instead of the browser's encoders — noticeably smaller files, slower, and downloads ~460 KB of codec the first time.",
      metaNote: "Metadata is not carried over — EXIF, GPS and colour profiles are dropped when the image is re-encoded. Output is sRGB.",
      queued: "In queue",
      output: "Output folder",
      outputPath: "~/Pictures/Pixl Tweak",
      change: "Change",
      total: "Total saved",
      go: "Convert",
      moreFiles: "Add more",
      converting: "Converting…",
      elapsed: "elapsed",
      convertingSub: "Working through your queue, hang tight.",
      cancel: "Cancel",
      cancelled: "Cancelled — {n} of {total} were finished.",
      doneTitle: "All done!",
      doneSub: "Converted {n} images, saved {saved}.",
      doneSubOne: "Converted 1 image, saved {saved}.",
      doneGrewSub: "Converted {n} images, but they grew by {grew}.",
      doneGrewSubOne: "Converted 1 image, but it grew by {grew}.",
      totalGrew: "Total added",
      downloads: "Downloads",
      failTitle: "Couldn't convert everything",
      failSub: "{n} of {total} files failed — see the list below.",
      errFormat: "{fmt} not supported here",
      errRead: "Couldn't read this file",
      errTooBig: "Too big for this browser ({dims})",
      again: "Convert more",
      filesIn: "files in queue",
      icoKeepOriginal: "Keep Original Resolution",
      icoIncludeSource: "Include source size in output",
      icoSizes: "ICO sizes to export",
      icoSizesHint: "Each size exports to its own folder",
      mergePDF: "Merge into one PDF file",
      clearAll: "Remove all files",
    },

    resize: {
      heading: "Resize dimensions",
      width: "Width",
      height: "Height",
      lock: "Lock aspect ratio",
      fit: "Fit mode",
      fits: ["Contain", "Cover", "Stretch"],
      fitTooltips: [
        "Fits inside, no crop",
        "Fills area, crops edges",
        "Exact size, may distort",
      ],
      upscale: "Allow upscaling",
      outputFormat: "Output format",
      transparent: "Preserve transparency",
      appliesToAll: "Applies to all {n} files",
      apply: "Apply",
    },

    compress: {
      heading: "Compress file size",
      target: "Target",
      targets: ["Web", "Email", "Print", "Custom"],
      mode: "Mode",
      modeQuality: "Quality",
      modeSize: "Target size",
      targetSize: "Maximum size",
      targetHint: "Searches for the highest quality that fits, by encoding — about seven tries.",
      targetMet: "Landed at {size}, quality {q}.",
      targetMissed: "Can't reach {target}. Smallest possible is {size} at quality 10.",
      compareHint: "Drag to compare",
      quality: "Quality",
      before: "Before",
      after: "After",
      savings: "Savings",
      originalQuality: "original quality",
      filesSingular: "file",
      filesPlural: "files",
      outputFormat: "Output format",
      reduceColors: "Reduce max colors (PNG)",
      reduceColorsHint: "Quantizes the palette — ideal for logos and icons",
      maxColors: "Max colors",
      start: "Start",
    },

    crop: {
      heading: "Crop & rotate",
      ratio: "Aspect ratio",
      ratios: ["Free", "1:1", "4:3", "16:9", "3:4", "9:16"],
      rotate: "Rotate",
      flipH: "Flip horizontal",
      flipV: "Flip vertical",
      reset: "Reset",
      apply: "Apply",
    },

    common: {
      go: "Start",
      ready: "Ready",
      saved: "saved",
    },

    footer: {
      ready: "Ready",
      offline: "Works offline",
      version: "v2.4.1",
    },
  },

  es: {
    appTitle1: "Pixl",
    appTitle2: "Tweak",
    appSub: "Convierte, redimensiona, comprime y recorta tus imágenes — ",

    tabs: {
      convert: "Convertir",
      resize: "Redimensionar",
      compress: "Comprimir",
      crop: "Recortar",
    },

    drop: {
      title: "Suelta tus imágenes aquí",
      hint: "Arrastra imágenes o carpetas, o haz clic para explorar — del resto nos encargamos nosotros.",
      browse: "Buscar archivos",
      folder: "Elegir carpeta",
      sample: "Probar con ejemplos",
      supported: "Formatos compatibles",
    },

    convert: {
      heading: "Convertir formato",
      format: "Formato de salida",
      quality: "Calidad",
      qualityHint: "Menor = archivo más ligero, mayor = más nítido",
      transparent: "Conservar transparencia",
      maxCompress: "Compresión máxima",
      maxCompressHint: "MozJPEG y OxiPNG en lugar de los codificadores del navegador — archivos bastante más pequeños, más lento, y descarga ~460 KB de códec la primera vez.",
      metaNote: "Los metadatos no se conservan — EXIF, GPS y perfiles de color se pierden al recodificar la imagen. La salida es sRGB.",
      queued: "En cola",
      output: "Carpeta de salida",
      outputPath: "~/Imágenes/Pixl Tweak",
      change: "Cambiar",
      total: "Total ahorrado",
      go: "Convertir",
      moreFiles: "Agregar más",
      converting: "Convirtiendo…",
      elapsed: "transcurrido",
      convertingSub: "Procesando tu cola, un momento.",
      cancel: "Cancelar",
      cancelled: "Cancelado — se completaron {n} de {total}.",
      doneTitle: "¡Listo!",
      doneSub: "Se convirtieron {n} imágenes, ahorraste {saved}.",
      doneSubOne: "Se convirtió 1 imagen, ahorraste {saved}.",
      doneGrewSub: "Se convirtieron {n} imágenes, pero crecieron {grew}.",
      doneGrewSubOne: "Se convirtió 1 imagen, pero creció {grew}.",
      totalGrew: "Total añadido",
      downloads: "Descargas",
      failTitle: "No se pudo convertir todo",
      failSub: "Fallaron {n} de {total} archivos — revisa la lista.",
      errFormat: "{fmt} no soportado aquí",
      errRead: "No se pudo leer este archivo",
      errTooBig: "Demasiado grande para este navegador ({dims})",
      again: "Convertir más",
      filesIn: "archivos en la cola",
      icoKeepOriginal: "Mantener resolución original",
      icoIncludeSource: "Incluir tamaño original en output",
      icoSizes: "Tamaños ICO a exportar",
      icoSizesHint: "Cada tamaño se exportará en su propia carpeta",
      mergePDF: "Unir en un solo PDF",
      clearAll: "Quitar todo",
    },

    resize: {
      heading: "Cambiar dimensiones",
      width: "Ancho",
      height: "Alto",
      lock: "Bloquear proporción",
      fit: "Modo de ajuste",
      fits: ["Contener", "Cubrir", "Estirar"],
      fitTooltips: [
        "Ajusta sin recortar",
        "Rellena, puede recortar",
        "Exacto, puede distorsionar",
      ],
      upscale: "Permitir ampliación",
      outputFormat: "Formato de salida",
      transparent: "Conservar transparencia",
      appliesToAll: "Se aplica a los {n} archivos",
      apply: "Aplicar",
    },

    compress: {
      heading: "Comprimir tamaño",
      target: "Destino",
      targets: ["Web", "Correo", "Impresión", "Personalizado"],
      mode: "Modo",
      modeQuality: "Calidad",
      modeSize: "Tamaño objetivo",
      targetSize: "Tamaño máximo",
      targetHint: "Busca la mejor calidad que quepa, codificando — unos siete intentos.",
      targetMet: "Quedó en {size}, calidad {q}.",
      targetMissed: "No se puede bajar de {target}. Lo más pequeño son {size} con calidad 10.",
      compareHint: "Arrastra para comparar",
      quality: "Calidad",
      before: "Antes",
      after: "Después",
      savings: "Ahorro",
      originalQuality: "calidad original",
      filesSingular: "archivo",
      filesPlural: "archivos",
      outputFormat: "Formato de salida",
      reduceColors: "Reducir colores máximos (PNG)",
      reduceColorsHint: "Cuantiza la paleta — ideal para logos e iconos",
      maxColors: "Máximo de colores",
      start: "Comprimir",
    },

    crop: {
      heading: "Recortar y rotar",
      ratio: "Proporción",
      ratios: ["Libre", "1:1", "4:3", "16:9", "3:4", "9:16"],
      rotate: "Rotar",
      flipH: "Voltear horizontal",
      flipV: "Voltear vertical",
      reset: "Restablecer",
      apply: "Aplicar",
    },

    common: {
      go: "Iniciar",
      ready: "Listo",
      saved: "ahorrados",
    },

    footer: {
      ready: "Listo",
      offline: "Funciona sin conexión",
      version: "v2.4.1",
    },
  },
};

window.COPY = COPY;
